board_arm:
    # publish all joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # position controllers
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint1
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint2
        pid: {p: 100.0, i: 0.01, d: 10.0}

    # velocity controllers
    joint1_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint1
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint2_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint2
        pid: {p: 100.0, i: 0.01, d: 10.0}
